# Generated by Django 2.2.28 on 2022-04-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockTickers', '0002_auto_20210512_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.IntegerField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('Credits', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
